apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  name: angular-sa-anyuid
roleRef:
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: angular-sa
  namespace: bowman-sw
userNames:
- system:serviceaccount:bowman-sw:angular-sa
